### ISSUE TITLE
Flickering when cmdheight=0

### ISSUE THREAD

**Issue by yutkat** [chen244/csv-tools.lua#2]
Screen flickers when moving the cursor with `cmdheight=0`.

https://user-images.githubusercontent.com/8683947/181196753-a1d59e0f-aabd-422b-baa0-63425396d5c2.mp4

### minimal init.lua

```lua
vim.cmd [[syntax enable]]
vim.cmd [[filetype plugin indent on]]

local install_path = vim.fn.stdpath('data')..'/site/pack/packer/opt/packer.nvim'
if vim.fn.empty(vim.fn.glob(install_path)) == 1 then
  vim.api.nvim_command('!git clone https://github.com/wbthomason/packer.nvim '..install_path)
end
vim.cmd [[packadd packer.nvim]]

-- Occurs when this option is present
vim.o.cmdheight = 0

local function load_plugins()
  return require('packer').startup(function()
    use {'wbthomason/packer.nvim', opt = true}
    use {'Decodetalkers/csv-tools.lua'}
  end)
end
load_plugins()
```

**Comment by Decodetalkers** [comment]
Please reupload the video ,it seems it is not uploaded successfully..

**Comment by Decodetalkers** [comment]
I have view the problem in nightly... I will try to find out the solution

**Comment by yutkat** [comment]
> Please reupload the video ,it seems it is not uploaded successfully..

I can see the video properly, but I upload it again just in case.

https://user-images.githubusercontent.com/8683947/181200603-8f8151f9-d840-456b-8b6b-d558c5465f0e.mp4

**Comment by Decodetalkers** [comment]
> > Please reupload the video ,it seems it is not uploaded successfully..
> 
> I can see the video properly, but I upload it again just in case.
> wf_220727-171128.mp4

https://github.com/Decodetalkers/csv-tools.lua/blob/master/lua/csvtools.lua#L121

problem happened when it try to clear highlight.. if you set clearafter= false ,it will not Flicker...

**Comment by Decodetalkers** [comment]
No , not because of it...

**Comment by Decodetalkers** [comment]
> > Please reupload the video ,it seems it is not uploaded successfully..
> 
> I can see the video properly, but I upload it again just in case.
> wf_220727-171128.mp4

https://github.com/Decodetalkers/csv-tools.lua/blob/master/lua/csvtools.lua#L197
I see , I use ":+1<CR>:lua ..." then everytime ,it call the cmdline.. But I have no idea how to call the function and move to the nextline with the keybinding..

**Comment by Decodetalkers** [comment]
FIxed. wait for a minite

**Comment by Decodetalkers** [comment]
> > Please reupload the video ,it seems it is not uploaded successfully..
> 
> I can see the video properly, but I upload it again just in case.
> wf_220727-171128.mp4

I think I fixed it

**Comment by yutkat** [comment]
I think this line is `-1`.

https://github.com/Decodetalkers/csv-tools.lua/commit/2dc56d09af8c7bb3f0509d17466a290adf2b3f52#diff-9f6f9e2b5a839bcd620bb16b9edf03d11646bdbceb600bfde93a5d73c9204f03R189

**Comment by Decodetalkers** [comment]
> I think this line is `-1`.
> 
> https://github.com/Decodetalkers/csv-tools.lua/commit/2dc56d09af8c7bb3f0509d17466a290adf2b3f52#diff-9f6f9e2b5a839bcd620bb16b9edf03d11646bdbceb600bfde93a5d73c9204f03R189
> 

Oop, I make a mistake.. But I am on the train now.. Can you make a PR for me?

**Comment by yutkat** [comment]
Resolved. Thank you :smile:
